### ISSUE TITLE
Missing Fragments edge case

### ISSUE THREAD

**Issue by suragnair** [timoast/sinto#31] opened 2021-07-23 22:47 UTC
Hi Tim, thanks for the package!

Here's a simple toy bam file on which I was running `sinto fragments`. The MAPQs, fragment lengths etc seem fine, but there's no output when I run:
`sinto fragments  -b lol.bam -f lol.frag`

[lol.bam.zip](https://github.com/timoast/sinto/files/6871503/lol.bam.zip)
This file has 5 read pairs. I see outputs when I add more read pairs.

I was tracing through the code and it's most likely an edge case here:
https://github.com/timoast/sinto/blob/9ac3e8c37ac7ec1f21ebdd0a48eaf1e255926bd7/sinto/fragments.py#L218-L224

The `fragment_dict` looks good per chromosome but somehow doesn't make it to `complete`. Not entirely sure of the logic but can look into it if you'd like. Thanks again.

**Comment by caleblareau** [comment] 2021-07-29 09:53
I dug into this, and here's what I think is happening:

At the comparison here for a sample read in Surag's bam file: https://github.com/timoast/sinto/blob/9ac3e8c37ac7ec1f21ebdd0a48eaf1e255926bd7/sinto/fragments.py#L258

these are the values:

```
{'J00118:471:H773LBBXY:1:1101:29000:1173': ['chr11', 65780099, 65780186, 'NNNNNNNNNNNNNNNN', True]}
current_position:  65780140
fragments[key][2]: 65780186
```

by the time the `findCompleteFragments` function is called, both the current position pointer and the fragments value are referring to the same read, but in different contexts. The current position is essentially the very beginning of the read whereas the fragments[key][2] is the very end of the read, plus the offset. Since Surag's reads are 51 bases and the Tn5 offset is already accounted for at this time, then you get the mismatch. 

I think the logic that you'd want to replace it with would be something like 

```
if (fragments[key][2] + d - READ_LENGTH - 5) <= current_position: 
```
where the 5 is to undo the Tn5 offset. I'm not sure how to best pull the READ_LENGTH in this function, so I just defined a variable to be 51 in a test case and confirmed that all of the values are now written as we'd expect. 

I can't quite tell the impact of this... The worst case scenario in my mind guess is that this throws away 1 read per chunk, and here, Surag only supplies 1 read per chromosome, hence the empty file. But maybe we only lose 1 read per chromosome (i.e. the very last one)?

**Comment by suragnair** [comment] 2021-07-30 07:24
Thanks Caleb, here's an extended bam 
[lol.more.bam.zip](https://github.com/timoast/sinto/files/6905747/lol.more.bam.zip)
with ~2000 read pairs. Running with relaxed thresholds

```bash
sinto fragments  -b lol.more.bam -f lol.more.frag -m 0 --max_distance 100000000  
```

returns a file with 2080 fragments. Conversely 

```bash
bamToBed -bedpe -i lol.namesort.bam.bam | awk '($1!=".")&&($4==$1)'  | wc -l
```

returns 2138 (even if you ensure min fragment length of 10). So it seems to be losing more than 1 per chromosome.

**Comment by timoast** [comment] 2021-07-30 16:11
Hi @suragnair, thanks for reporting and thanks @caleblareau for looking into this. I think what was happening here was that the fragments at the very end of the chromosome were not being recorded due to the bug that Caleb mentioned. I made a simple fix that forces all the fragments currently being held to be evaluated once the end of the chromosome is reached, which as far as I can tell fixes this issue but please let me know if not.

This bug would result in fragments with an end position close to the end of the chromosome (within the length of the read) being dropped, which typically is a small number of fragments per chromosome (can be >1, but typically not a lot of fragments).

If this looks good to you, I can close the issue and release on PyPI

**Comment by suragnair** [comment] 2021-07-30 19:47
This looks good, thanks a bunch!

**Closed** 2021-07-30 19:48 UTC
